package com.aqhi.model;


import java.util.ArrayList;
import java.util.List;

public class Employee {
	
	private List<URole> roles = new ArrayList();
	
	
    public List<URole> getRoles() {
		return roles;
	}

	public void setRoles(List<URole> roles) {
		this.roles = roles;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empl_id
     *
     * @mbg.generated
     */
    private Long empl_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.salt
     *
     * @mbg.generated
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.mobile_phone
     *
     * @mbg.generated
     */
    private String mobile_phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.photo
     *
     * @mbg.generated
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.deptno
     *
     * @mbg.generated
     */
    private Long deptno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.account_status
     *
     * @mbg.generated
     */
    private Byte account_status;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    public Employee(Long empl_id, String nickname, String password, String salt, String email, String mobile_phone, String photo, Long deptno, Byte account_status) {
        this.empl_id = empl_id;
        this.nickname = nickname;
        this.password = password;
        this.salt = salt;
        this.email = email;
        this.mobile_phone = mobile_phone;
        this.photo = photo;
        this.deptno = deptno;
        this.account_status = account_status;
    }

    public Employee() {
		// TODO Auto-generated constructor stub
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empl_id
     *
     * @return the value of employee.empl_id
     *
     * @mbg.generated
     */
    public Long getEmpl_id() {
        return empl_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.nickname
     *
     * @return the value of employee.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.password
     *
     * @return the value of employee.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.salt
     *
     * @return the value of employee.salt
     *
     * @mbg.generated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.email
     *
     * @return the value of employee.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.mobile_phone
     *
     * @return the value of employee.mobile_phone
     *
     * @mbg.generated
     */
    public String getMobile_phone() {
        return mobile_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.photo
     *
     * @return the value of employee.photo
     *
     * @mbg.generated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.deptno
     *
     * @return the value of employee.deptno
     *
     * @mbg.generated
     */
    public Long getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.account_status
     *
     * @return the value of employee.account_status
     *
     * @mbg.generated
     */
    public Byte getAccount_status() {
        return account_status;
    }

	public void setEmpl_id(Long empl_id) {
		this.empl_id = empl_id;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setMobile_phone(String mobile_phone) {
		this.mobile_phone = mobile_phone;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public void setDeptno(Long deptno) {
		this.deptno = deptno;
	}

	public void setAccount_status(Byte account_status) {
		this.account_status = account_status;
	}

	@Override
	public String toString() {
		return "Employee [roles=" + roles + ", empl_id=" + empl_id + ", nickname=" + nickname + ", password=" + password
				+ ", salt=" + salt + ", email=" + email + ", mobile_phone=" + mobile_phone + ", photo=" + photo
				+ ", deptno=" + deptno + ", account_status=" + account_status + "]";
	}
    
    
}