package com.aqhi.model;

public class URole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_role.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_role.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_role.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated
     */
    public URole(Long id, String name, String type) {
        this.id = id;
        this.name = name;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_role.id
     *
     * @return the value of u_role.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_role.name
     *
     * @return the value of u_role.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_role.type
     *
     * @return the value of u_role.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

	public void setId(Long id) {
		this.id = id;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Override
	public String toString() {
		return "URole [id=" + id + ", name=" + name + ", type=" + type + "]";
	}
    
    
}