package com.aqhi.model;

public class UUserRole {
	
	private URole role;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user_role.uid
     *
     * @mbg.generated
     */
    private Long uid;

    @Override
	public String toString() {
		return "UUserRole [role=" + role + ", uid=" + uid + ", rid=" + rid + "]";
	}

	public URole getRole() {
		return role;
	}

	public void setRole(URole role) {
		this.role = role;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public void setRid(Long rid) {
		this.rid = rid;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user_role.rid
     *
     * @mbg.generated
     */
    private Long rid;
    
    public UUserRole(){}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_role
     *
     * @mbg.generated
     */
    public UUserRole(Long uid, Long rid , URole role) {
        this.uid = uid;
        this.rid = rid;
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_role.uid
     *
     * @return the value of u_user_role.uid
     *
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_role.rid
     *
     * @return the value of u_user_role.rid
     *
     * @mbg.generated
     */
    public Long getRid() {
        return rid;
    }
}