package com.aqhi.mapper;

import com.aqhi.model.EmployeeInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface EmployeeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated
     */
    @Delete({
        "delete from employee_info",
        "where empl_id = #{empl_id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long empl_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated
     */
    @Insert({
        "insert into employee_info (empl_id, gender, ",
        "true_name, identify, ",
        "home_address, live_address, ",
        "education, political_status, ",
        "graduated_school, telephone, ",
        "qq, we_chat, register_time)",
        "values (#{empl_id,jdbcType=BIGINT}, #{gender,jdbcType=TINYINT}, ",
        "#{true_name,jdbcType=VARCHAR}, #{identify,jdbcType=VARCHAR}, ",
        "#{home_address,jdbcType=VARCHAR}, #{live_address,jdbcType=VARCHAR}, ",
        "#{education,jdbcType=VARCHAR}, #{political_status,jdbcType=VARCHAR}, ",
        "#{graduated_school,jdbcType=VARCHAR}, #{telephone,jdbcType=VARCHAR}, ",
        "#{qq,jdbcType=VARCHAR}, #{we_chat,jdbcType=VARCHAR}, #{register_time,jdbcType=TIMESTAMP})"
    })
    int insert(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated
     */
    int insertSelective(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "empl_id, gender, true_name, identify, home_address, live_address, education, ",
        "political_status, graduated_school, telephone, qq, we_chat, register_time",
        "from employee_info",
        "where empl_id = #{empl_id,jdbcType=BIGINT}"
    })
    @ResultMap("com.aqhi.mapper.EmployeeInfoMapper.BaseResultMap")
    EmployeeInfo selectByPrimaryKey(Long empl_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated
     */
    @Update({
        "update employee_info",
        "set gender = #{gender,jdbcType=TINYINT},",
          "true_name = #{true_name,jdbcType=VARCHAR},",
          "identify = #{identify,jdbcType=VARCHAR},",
          "home_address = #{home_address,jdbcType=VARCHAR},",
          "live_address = #{live_address,jdbcType=VARCHAR},",
          "education = #{education,jdbcType=VARCHAR},",
          "political_status = #{political_status,jdbcType=VARCHAR},",
          "graduated_school = #{graduated_school,jdbcType=VARCHAR},",
          "telephone = #{telephone,jdbcType=VARCHAR},",
          "qq = #{qq,jdbcType=VARCHAR},",
          "we_chat = #{we_chat,jdbcType=VARCHAR},",
          "register_time = #{register_time,jdbcType=TIMESTAMP}",
        "where empl_id = #{empl_id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(EmployeeInfo record);
}