package com.aqhi.mapper;

import com.aqhi.model.Employee;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    @Delete({
        "delete from employee",
        "where empl_id = #{empl_id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long empl_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    @Insert({
        "insert into employee (empl_id, nickname, ",
        "password, salt, ",
        "email, mobile_phone, ",
        "photo, deptno, account_status)",
        "values (#{empl_id,jdbcType=BIGINT}, #{nickname,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{salt,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{mobile_phone,jdbcType=VARCHAR}, ",
        "#{photo,jdbcType=VARCHAR}, #{deptno,jdbcType=BIGINT}, #{account_status,jdbcType=TINYINT})"
    })
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "empl_id, nickname, password, salt, email, mobile_phone, photo, deptno, account_status",
        "from employee",
        "where empl_id = #{empl_id,jdbcType=BIGINT}"
    })
    @ResultMap("com.aqhi.mapper.EmployeeMapper.BaseResultMap")
    Employee selectByPrimaryKey(Long empl_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    @Update({
        "update employee",
        "set nickname = #{nickname,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "salt = #{salt,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "mobile_phone = #{mobile_phone,jdbcType=VARCHAR},",
          "photo = #{photo,jdbcType=VARCHAR},",
          "deptno = #{deptno,jdbcType=BIGINT},",
          "account_status = #{account_status,jdbcType=TINYINT}",
        "where empl_id = #{empl_id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Employee record);
    
    
    @Select({
        "select",
        "empl_id, nickname, password, salt, email, mobile_phone, photo, deptno, account_status",
        "from employee",
        "where nickname = #{nickname,jdbcType=VARCHAR}"
    })
    @ResultMap("com.aqhi.mapper.EmployeeMapper.BaseResultMap")
    Employee selectByNickname(String nickname);
    
    
    @Select({
        "select",
        "empl_id, nickname, password, salt, email, mobile_phone, photo, deptno, account_status",
        "from employee"
    })
    @ResultMap("com.aqhi.mapper.EmployeeMapper.BaseResultMap")
    List<Employee> selectEmployee();
    
    
    @Select({
        "select",
        "empl_id, nickname, password, salt, email, mobile_phone, photo, deptno, account_status",
        "from employee",
        "where empl_id = #{empl_id,jdbcType=BIGINT}"
    })
    @ResultMap("com.aqhi.mapper.EmployeeMapper.EmployeeMap")
    Employee selectByEmplId(Long empl_id);
}